2(21) 
Дана целочисленная прямоугольная матрица. Определить количество столбцов, не содержащих ни одного нулевого элемента. Характеристикой строки целочисленной матрицы назовем сумму ее положительных четных элементов. Переставляя строки заданной матрицы, расположить их в соответствии с ростом характеристик.

In [2]:
import numpy as np

In [205]:
array = np.random.randint(-10,15,(4,6))
print(array)

[[ 12   0   0   9   4  13]
 [  3   9 -10   0  -6  12]
 [ 14   1   6   2  11   9]
 [ 11   7   9  -6  -7   9]]


The np.all() function tests if all elements in an array are True.

In [206]:
non_zero = np.all(array, axis = 0)
non_zero = non_zero[non_zero == True]
print("количество ненулевых столбцов = ",len(non_zero))

количество ненулевых столбцов =  3


создадим отдельный массив, в котором находятся характеристики каждой строки

In [210]:
sum_srt = np.where(((array > 0) & (array % 2 == 0)),1,0) * array
sum_srt = sum_srt.sum(axis = 1)
print('массив, в котором находятся характеристики каждой строки:\n',sum_srt)
print('\n\n')
print('заданная матрица, расположенная в соот-ии с ростом характеристик:\n',array[sum_srt.argsort()])

массив, в котором находятся характеристики каждой строки:
 [16 12 22  0]



заданная матрица, расположенная в соот-ии с ростом характеристик:
 [[ 11   7   9  -6  -7   9]
 [  3   9 -10   0  -6  12]
 [ 12   0   0   9   4  13]
 [ 14   1   6   2  11   9]]
