2(21) 
Дана целочисленная прямоугольная матрица. Определить количество столбцов, не содержащих ни одного нулевого элемента. Характеристикой строки целочисленной матрицы назовем сумму ее положительных четных элементов. Переставляя строки заданной матрицы, расположить их в соответствии с ростом характеристик.

In [3]:
import numpy as np

In [11]:
array = np.random.randint(-10,15,(4,6))
print(array)

[[  0  -9   0   9  -1   0]
 [ -8  -9   3   8 -10  -9]
 [ -5  14  12  -6  -1   6]
 [ -1  -2  13  -8  -3   2]]


The np.all() function tests if all elements in an array are True.

In [15]:
non_zero = np.all(array, axis = 0)
non_zero = non_zero[non_zero == True]
print("количество ненулевых столбцов = ",len(non_zero))

количество ненулевых столбцов =  3


создадим отдельный массив, в котором находятся характеристики каждой строки

In [13]:
sum_srt = np.where(((array > 0) & (array % 2 == 0)),1,0) * array
sum_srt = sum_srt.sum(axis = 1)
print('массив, в котором находятся характеристики каждой строки:\n',sum_srt)
print('\n\n')
print('заданная матрица, расположенная в соот-ии с ростом характеристик:\n',array[sum_srt.argsort()])

массив, в котором находятся характеристики каждой строки:
 [ 0  8 32  2]



заданная матрица, расположенная в соот-ии с ростом характеристик:
 [[  0  -9   0   9  -1   0]
 [ -1  -2  13  -8  -3   2]
 [ -8  -9   3   8 -10  -9]
 [ -5  14  12  -6  -1   6]]
